### ISSUE TITLE
A question about opening the ADaM XPT files2

### ISSUE THREAD

**Issue by reportbuilder** [elong0527/ectddemo#1]
Dear Yilong,

I was just trying to open the XPT files from several places in Git, for example from the following location:
https://github.com/elong0527/ectddemo/tree/master/m5/datasets/ectddemo/analysis/adam/datasets

But both R and SAS failed to open them, so I got error messages. Would you give me a hint on how do I open them, please? Below are the examples of the calls (using reprex).

TIA
Rao

adae <- sasxport.get("adae.xpt")
#> Error in sasxport.get("adae.xpt"): could not find function "sasxport.get"

adae <- read_sas("adae.xpt")
#> Error in read_sas("adae.xpt"): could not find function "read_sas"

**Comment by elong0527** [comment]
You need to install and load required R package before you can use functions.

You can find more information by searching the error messages.
